"""Template rendering tests for ReportGenerator using _body_override (no LLM call)."""

from datetime import date
from unittest.mock import AsyncMock

from solar_report.analysis.models import PeriodSummary
from solar_report.config import SystemConfig
from solar_report.llm.client import AnthropicClient
from solar_report.report.generator import ReportGenerator

FOOTER = (
    "Report generated by solar-report. Numbers are computed from source data; "
    "interpretive text is model-generated."
)

SYSTEM = SystemConfig(
    name="My rooftop PV",
    location="Turin, Italy",
    installed_kwp=6.0,
    panels=15,
    tilt_deg=30,
    azimuth_deg=180,
)

SUMMARY = PeriodSummary(
    start_date=date(2026, 7, 13),
    end_date=date(2026, 7, 19),
    total_kwh=151.2,
    daily_values=[(date(2026, 7, 13 + offset), 21.6) for offset in range(7)],
    best_day=date(2026, 7, 15),
    worst_day=date(2026, 7, 17),
    baseline_daily_kwh=22.0,
)

BODY = "## Overview\n\nA quiet, sunny week for the system.\n"


def _generator() -> tuple[ReportGenerator, AsyncMock]:
    client = AsyncMock(spec=AnthropicClient)
    return ReportGenerator(client), client


async def test_markdown_output_wraps_body_with_metadata_and_footer() -> None:
    generator, client = _generator()

    result = await generator.generate(
        SYSTEM,
        SUMMARY,
        period_label="week",
        output_format="markdown",
        _body_override=BODY,
    )

    client.generate.assert_not_awaited()
    assert result.startswith("# Solar Report — My rooftop PV\n")
    assert "**Period:** 2026-07-13 to 2026-07-19" in result
    assert "**Generated:** " in result
    assert "Turin, Italy" in result
    assert "6.0 kWp" in result
    assert BODY.strip() in result
    assert FOOTER in result


async def test_html_output_converts_body_markdown_to_html() -> None:
    generator, client = _generator()

    result = await generator.generate(
        SYSTEM,
        SUMMARY,
        period_label="week",
        output_format="html",
        _body_override=BODY,
    )

    client.generate.assert_not_awaited()
    assert result.startswith("<!DOCTYPE html>")
    assert "<h1>Solar Report — My rooftop PV</h1>" in result
    assert "<h2>Overview</h2>" in result
    assert "A quiet, sunny week for the system." in result
    assert "Period: 2026-07-13 to 2026-07-19" in result
    assert FOOTER in result
    # The raw Markdown heading must not leak through unconverted.
    assert "## Overview" not in result


async def test_html_output_escapes_system_metadata() -> None:
    generator, _ = _generator()
    system = SYSTEM.model_copy(update={"name": "PV <script>alert(1)</script>"})

    result = await generator.generate(
        system,
        SUMMARY,
        period_label="week",
        output_format="html",
        _body_override=BODY,
    )

    assert "<script>alert(1)</script>" not in result
    assert "&lt;script&gt;" in result


async def test_markdown_omits_location_when_not_configured() -> None:
    generator, _ = _generator()
    system = SYSTEM.model_copy(update={"location": None})

    result = await generator.generate(
        system,
        SUMMARY,
        period_label="week",
        output_format="markdown",
        _body_override=BODY,
    )

    assert "**System:** 6.0 kWp" in result
